### ISSUE TITLE
option to calculate the workload by days

### ISSUE THREAD

**Issue by uart-aplex** [xmera-circle/redmine_workload#10]
Hi,
The tasks in our redmine project management does not calculate the workload in hours, but in days, so this “estimated time field” is not used(hidden) in all trackers, and makes this plugin unusable.

Is it possible to have an option to calculate the workload by days?

**Comment by mboremski** [comment]
Hey @uart-aplex,
this plugin only uses the redmine-core-feature to plan and track time.
This core-feature only relys on hour-basis and not on complete days.

Can you explain how you use days to track efforts?
Do you just count the number of workdays?

Maybe @liaham or I can give youa hint on how to adapt this plugin for your needs.

**Comment by uart-aplex** [comment]
Yes, we only count the number of workdays by the date duration of tasks. Usually each of our tasks takes several or dozens of working days to complete, and does not need to be calculated in hours.

![image](https://user-images.githubusercontent.com/24597310/192766045-7491fd7b-9e8d-4bc0-bb0e-3a1c9865d1db.png)

**Comment by mboremski** [comment]
Thanks for clarification.
Redmine-core does not calculate the `Duration` of a task.
It looks you are using a plugin for your `GanttX`-view and this one calculates the `Duration`.
(What plugin do you use here?)

To use this parameter we would have to rely on this plugin.
Or we would have to calculate the duration by our plugin.
Both ways would kind of erode the goal to use redmine-core-features to feed our plugin with informations.

Maybe, as a workaround you could calculate estimated hours by the `Duration` (e.g. times 8h) and updtae them manually.
Unfortunately tihs would be an extra step for you that needs to be done when planning tasks.

I don't see much other ways to help you out here.

Best regards,
Markus

**Comment by uart-aplex** [comment]
Is it possible that if the Estimated time field is not filled, then there is an option to automatically replace the Estimated time with a daily working hours(filled in the configuration of this plugin) to calculate the workload? Otherwise, if in order to use this plugin, forcing the user to fill in the duration times daily working hour for each task will make the user feel a lot of work burden. 

The plugin with duration calculation we are using is RedmineX Gantt.

**Comment by mboremski** [comment]
In near future (around november) we will do an update to be compatible with redmine5.x (see #6 )
I will discuss your guess with @liaham while we do this.

**Comment by kevinguiro** [comment]
Buenos dias ya es compatible con la version 4.2 de redmine

**Comment by liaham** [comment]
> Buenos dias ya es compatible con la version 4.2 de redmine

Yes, it is. Thank you @kevinguiro for pointing out on this. We will add a note to the README.

**Comment by mboremski** [comment]
As pointed out before redmine it self is designed to use estimations on work and calculate workloa based on this plan.
To some kind of guess estimations by available times of a user is not intended.

So we decided to reject this feature-request.
Please leave a note if we missed something here.

**Comment by akshay2910-git** [comment]
I am getting fewer users listed in the select user(s) section. Also, I am not able to list workload for all user belonging to the group. Can anyone suggest how to fix it.
Below is the environment 

Environment:
  Redmine version                5.0.5.stable
  Ruby version                   3.1.4-p223 (2023-03-30) [x86_64-linux]
  Rails version                  6.1.7.2
redmine_workload               3.0.2

**Comment by liaham** [comment]
Hi @akshay2910-git,

Thank you for your report.

This issue is closed. Please create a new issue for your problem.

Best Regards
@liaham
