### ISSUE TITLE
Como Administrador

### ISSUE THREAD

**Issue by kevinguiro** [xmera-circle/redmine_workload#11]
Como administrador de la herramienta no me carga todos los usuarios para ver sus actividades o tengo que hacer algo mas en la configuracion

**Comment by liaham** [comment]
Hi @kevinguiro,

Thank you very much for opening your first issue here! Contributions are always welcome. 

But please write your issue in English. Otherwise it is almost impossible to help you. 

Best Regards,
Liane

**Comment by kevinguiro** [comment]
Hi Liaham

As administrator of the tool it does not load all the users to see their activities or I have to do something else in the configuration
those users only appear if there are many

Best Regards,
Pedro
![Screenshot_1](https://user-images.githubusercontent.com/115120826/194899641-9d8672a1-7e9d-4d0a-9fe9-e9d9648f8282.jpg)

**Comment by mboremski** [comment]
Hey @kevinguiro,
could you please verify that every user in the Group `Administrator Admin` has defined a `main group`?
In [README.md](https://github.com/xmera-circle/redmine_workload/blob/master/README.md) please see point 3 in the chapter [#configuration](https://github.com/xmera-circle/redmine_workload#configuration).

The `main group` needs to be set to make the plugin work properly on user-groups.

**Comment by kevinguiro** [comment]
Listo tiene que ser por grupos Generados por el administradorGracias Ready has to be in groups Administrator generatedThank youEl 10 oct. 2022 12:25 p. m., Markus Boremski ***@***.***> escribió:
Hey @kevinguiro,
could you please verify that every user in the Group Administrator Admin has defined a main group?
In README.md please see point 3 in the chapter #configuration.
The main group needs to be set to make the plugin work properly on user-groups.

**Comment by kevinguiro** [comment]
> Hey @kevinguiro, could you please verify that every user in the Group `Administrator Admin` has defined a `main group`? In [README.md](https://github.com/xmera-circle/redmine_workload/blob/master/README.md) please see point 3 in the chapter [#configuration](https://github.com/xmera-circle/redmine_workload#configuration).
> 
> The `main group` needs to be set to make the plugin work properly on user-groups.

I did not understand why I already enabled all the permissions in the profiles and the page shows me this error and in the log this

No entendi por que ya habilite todos los permisos en los perfiles y la pagina me muestra este error y en el log esto 
![lp](https://user-images.githubusercontent.com/115120826/195158573-da3ee336-abb6-4a0d-99e1-83f2d18ad720.jpg)
![log](https://user-images.githubusercontent.com/115120826/195159091-b08815be-85f6-46f1-9b7e-d46b9b163b27.jpg)

**Comment by mboremski** [comment]
Hey @kevinguiro, could you please add the logs you are mentioning?
Right now I am not sure what issue you are facing.
Also, as Liane already pointed out, please write in english only.

Thank you

**Comment by kevinguiro** [comment]
Hey @mboremski 
![log de wl](https://user-images.githubusercontent.com/115120826/196259954-d6136fec-1c1e-4836-9897-12ad9faa99c7.jpg)
![pagina  wl](https://user-images.githubusercontent.com/115120826/196259959-8b0541d9-cdb0-43eb-90bc-643757fce1d9.jpg)

My user has all the options enabled in his profile but he does not open the page, he sends screens and my version of Redmine

Environment:
  Redmine version                4.2.5.stable
  Ruby version                   2.7.6-p219 (2022-04-12) [x86_64-linux]
  Rails version                  5.2.6.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.14.1
  Mercurial                      5.6.1
  Bazaar                         3.1.0
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  microsoft_project_connector    1.0.7
  redmine_dashboard              2.12.0
  redmine_indicator              0.2.16
  redmine_issue_evm              4.6.0
  redmine_monitoring_controlling 0.1.1
  redmine_reports                0.0.1
  redmine_risks                  1.4.1
  redmine_team_resource          0.4.3
  redmine_workload               2.0.1
  remove_top_menu_help           0.0.1
  scrum                          0.20.0
  time_logger                    0.5.4

**Comment by liaham** [comment]
Hi @kevinguiro,

Thank you for reporting the error. 

I put your description into a new ticket (#13) in order to track that easier. 

It will take a while until this problem will be fixed. 

As a workaround you should check all possible settings very carefully.  You should also save the plugin settings even when you accepted the defaults. There is anywhere a value missing.

Hope, something will help you until the code is fixed.

Best Regards,
liaham

**Comment by kevinguiro** [comment]
The problem was understood
