### ISSUE TITLE
Nil error in WorkloadsHelper#load_class_for_hours

### ISSUE THREAD

**Issue by liaham** [xmera-circle/redmine_workload#13]
comparison of Float with nil failed

---

Hey @mboremski 
![log de wl](https://user-images.githubusercontent.com/115120826/196259954-d6136fec-1c1e-4836-9897-12ad9faa99c7.jpg)
![pagina  wl](https://user-images.githubusercontent.com/115120826/196259959-8b0541d9-cdb0-43eb-90bc-643757fce1d9.jpg)

My user has all the options enabled in his profile but he does not open the page, he sends screens and my version of Redmine

Environment:
  Redmine version                4.2.5.stable
  Ruby version                   2.7.6-p219 (2022-04-12) [x86_64-linux]
  Rails version                  5.2.6.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.14.1
  Mercurial                      5.6.1
  Bazaar                         3.1.0
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  microsoft_project_connector    1.0.7
  redmine_dashboard              2.12.0
  redmine_indicator              0.2.16
  redmine_issue_evm              4.6.0
  redmine_monitoring_controlling 0.1.1
  redmine_reports                0.0.1
  redmine_risks                  1.4.1
  redmine_team_resource          0.4.3
  redmine_workload               2.0.1
  remove_top_menu_help           0.0.1
  scrum                          0.20.0
  time_logger                    0.5.4

_Originally posted by @kevinguiro in https://github.com/xmera-circle/redmine_workload/issues/11#issuecomment-1281333474_

**Comment by kevinguiro** [comment]
Hi @liaham @mboremski 
![no me aparecen un grupo principal](https://user-images.githubusercontent.com/115120826/197082153-fc50b4b0-a294-465b-8c19-cf974df60884.jpg)

Why does the main group not appear in the configuration
What do I need to configure?

**Comment by mboremski** [comment]
Dear @kevinguiro, your last messgae is not related to the focus of this issue.
We are trying to keep different things seperated in this repo.

Please report your findings in a seperate issue or use the already very general issue #11.
Thank you.

PS: I will delete your comment soon to make this issue atomic again.

**Comment by kevinguiro** [comment]
Ok s
an apology I will change it as you tell me
Thank you.

**Comment by mboremski** [comment]
Dear @liaham, I am not sure what I can add or do here.
Do you need more informations to replicate this issue?

Unfortunately I am facing this one some times and need to remove teammembers to work around.

**Comment by mboremski** [comment]
Can be replicated by setting a user to absent for a long time / leaving copmany:
![grafik](https://user-images.githubusercontent.com/13338772/215059736-800f165d-deb3-467e-8f2a-5eeb79748a37.png)
