### ISSUE TITLE
Using Postgres: table wl_national_holidays cannot be used: column END is a reserved keyword

### ISSUE THREAD

**Issue by qbicode** [xmera-circle/redmine_workload#16]
Hi team,
I'm using postgres as database.
I cannot usse the workload plugin, because the table wl_national_holidays is using the column name END. This is a resreved keyword in Postgres and produces an error:

ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  syntax error at or near "end"
LINE 1: ...tional_holidays" WHERE (start <= '2022-12-26' AND end >= '20...
                                                             ^
: SELECT  1 AS one FROM "wl_national_holidays" WHERE (start <= '2022-12-26' AND end >= '2022-12-26') LIMIT $1):

Could you please fix this?
Cheers. 
Steffen

**Comment by liaham** [comment]
Hi Steffen,

Thank you very much for this information!  

Would you mind to prepare a pull request on this topic? 

Would be so helpful for all users when you could support in maintenance ...

Best Regards,
Liane
