### ISSUE TITLE
Update Workloads (spent time)

### ISSUE THREAD

**Issue by ydelgadoplata** [xmera-circle/redmine_workload#28]
Greetings development team!

There's an idea circling on my mind and is about updating the workloads of each member, taking into account the spent time reported per issue/task per day.

For example, to calculate the workloads the Start, end and estimate time need to be filled, but I noticed that if I report 1 hour of spent time for one of the tasks/Issues I have assigned, the workload is not updated. Instead of updating the workload, the workload is getting increase.

It would be really great, if the workload is updated taking into account the spent time per each issue/task. In this way, me, as a Project Manager, could decide which member of my team have less or more workload in order to assign or reduce work.

Thanks for your attention and please, let me know if this could be possible to make a reality, it will help us a lot!

Best Regards!

**Comment by ydelgadoplata** [comment]
@mboremski I think you're right. I've also configured the `%done` to change automatically with the `status` of the task, so I'm actually updating the statuses in order to validate the correct status of the tasks. It seems to work for me and for what I need to do.

Thanks a lot for the clarification!

**Comment by mboremski** [comment]
Glad to read your reply.
Will close this one.
