### ISSUE TITLE
style.ccs - border not dashed correctly for holiday.today

### ISSUE THREAD

**Issue by mboremski** [xmera-circle/redmine_workload#29]
Today we have:
https://github.com/xmera-circle/redmine_workload/blob/753bc8c14184cf1dfb742e838b0763c9f5b284f5/assets/stylesheets/style.css#L315-L318

`border-left: 2px solid red;` leads to this inconsistency in visualisation if someone has holliday:
![grafik](https://github.com/xmera-circle/redmine_workload/assets/13338772/d991e4c3-e325-42fa-9582-e27acb2d663e)

We should change to the same format like here:
https://github.com/xmera-circle/redmine_workload/blob/753bc8c14184cf1dfb742e838b0763c9f5b284f5/assets/stylesheets/style.css#L269-L273

@liaham, if OK four you I would change that directly in develop?

**Comment by mboremski** [comment]
@liaham, this line should have been removed:
https://github.com/xmera-circle/redmine_workload/blob/develop/assets/stylesheets/style.css#L318 🙈

**Comment by liaham** [comment]
@mboremski Makes sense!
