### ISSUE TITLE
Redmine 5.0.3 instalation fail

### ISSUE THREAD

**Issue by dskibarko** [xmera-circle/redmine_workload#31]
May be need more detailed installation description?
I have fail
![workoad_installation_issue](https://github.com/xmera-circle/redmine_workload/assets/20500604/e0363808-0bc2-4194-bc12-e4da3bbf8eec)

**Comment by mboremski** [comment]
Hey, what database do you use?

**Comment by akshay2910-git** [comment]
I am getting fewer users listed in the select user(s) section. Also, I am not able to list workload for all user belonging to the group. Can anyone suggest how to fix it.
Below is the environment

Environment:
Redmine version 5.0.5.stable
Ruby version 3.1.4-p223 (2023-03-30) [x86_64-linux]
Rails version 6.1.7.2
redmine_workload 3.0.2

**Comment by liaham** [comment]
Hi @akshay2910-git,

Thank you for your report.

This issue refers to another topic. Please create a new issue for your problem.

Best Regards
@liaham

**Comment by liaham** [comment]
Hi @dskibarko,
This issue has no response for several months. Therefore, it will be closed for now. Feel free to reopen it or create a new issue when the problem persists.

Best Regards
@liaham
