### ISSUE TITLE
[Bug]: Reserved word in postgres

### ISSUE THREAD

**Issue by GetxoSystems** [xmera-circle/redmine_workload#34]
### Contact Details

jortizdezarate@getxo.eus

### What did you expect?

release 3.0.2. hasn't fixed it 
003_create_wl_national_holidays.rb

class CreateWlNationalHolidays < ActiveRecord::Migration[5.2]
  def change
    create_table  :wl_national_holidays do |t|
      t.date      :start, null: false
      t.date      :end, null: false     ---> field name is end, so same error
      t.string    :reason, null: false
    end
  end
end

### What has happend instead?

same error

### What could be a possible solution?

explained in my previous issue

### How can we reproduce the problem?

postgres database

### In what environment are you running the plugin?

the same with plugin release  3.0.2

### Version

1.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GetxoSystems** [comment]
[es.yml.txt](https://github.com/xmera-circle/redmine_workload/files/13816734/es.yml.txt)
translation to spanish (spain)

**Comment by liaham** [comment]
Hi @GetxoSystems,

Did you try the latest release?

The postgress issue is fixed here: https://github.com/xmera-circle/redmine_workload/blob/76cb4bd513652d66d3e9545c1bc807de603059e6/lib/redmine_workload/wl_date_tools.rb#L80C1-L88C8.

Please note, that you also need to install Ruby: https://github.com/xmera-circle/redmine_workload#workday-settings.

Let me know if it runs as expected after your trial.

Best Regards,
@liaham 

P.S. Thank you for your Spanish translations! :)

**Comment by GetxoSystems** [comment]
Hi,
I tested last versión, it doesn´t work
This is due to last debían 12 distribution that includes ruby 3.0.1 so the patch doesnt work
I’ll wait untill debían upgrades ruby to at least 3.1
Anyway , is there any problem changing field names?
Regards




Julio Ortiz de Zarate Crespo
Telekomunikazio- Ingeniaria / Ingeniero/a de Telecomunicación
Gobernu Ireki eta Modernizazio Arloa / Área de Gobierno Abierto y Modernización

[cid:Escudo_7cbd05f0-d588-4757-9edb-9bd982e4fe2c.jpg]
[cid:bizi_7737e9f3-4d71-4a50-bdf8-7251a76e3760.jpg].    .

✆ +34944660218 / 3450<tel:3450>
✉ ***@***.******@***.***> Ⓦ www.getxo.eus<https://www.getxo.eus/>
[cid:ubicacion2_28d46b49-206c-4d8c-b19d-4ef2fe4c4a86.png] Basagoiti Etorbidea, 20 · 48992 · Getxo · Bizkaia


[cid:036_sm_fb_a1347472-45be-4a0b-af83-b901fa688c57.png]<https://www.facebook.com/GetxoUdala/>  [cid:logo-black_71f100eb-1275-4930-84b5-c65aa15e57ec.png] <https://twitter.com/getxoudala>   [cid:036_sm_y2_45d41b4c-7f16-42de-b619-b5cde39239df.png] <https://www.youtube.com/channel/UChEUKdARrLu5ylXvJFUrccQ>   <https://www.instagram.com/user_name_here> .
.

De: Liane Hampe ***@***.***
Enviado el: miércoles, 3 de enero de 2024 9:43
Para: xmera-circle/redmine_workload
CC: Julio Ortiz de Zarate Crespo; Mention
Asunto: Re: [xmera-circle/redmine_workload] [Bug]: Reserved word in postgres (Issue #34)


Hi @GetxoSystems<https://github.com/GetxoSystems>,

Did you try the latest release?

The postgress issue is fixed here: https://github.com/xmera-circle/redmine_workload/blob/76cb4bd513652d66d3e9545c1bc807de603059e6/lib/redmine_workload/wl_date_tools.rb#L80C1-L88C8.

Please note, that you also need to install Ruby: https://github.com/xmera-circle/redmine_workload#workday-settings.

Let me know if it runs as expected after your trial.

Best Regards,
@liaham<https://github.com/liaham>

P.S. Thank you for your Spanish translations! :)

**Comment by liaham** [comment]
Hi @GetxoSystems,

There should be no problem changing table column names and the code where these names are used.

Feel free to submit a Pull Request for this change. 

We will be happy to merge it when it passes all the tests.

Best Regards
@liaham

**Comment by GetxoSystems** [comment]
Liane,
Upgraded Ubuntu from lts jammy to lunar , versión ruby changed to 3.1
Plugin now works correctly
Regards



Julio Ortiz de Zarate Crespo
Telekomunikazio- Ingeniaria / Ingeniero/a de Telecomunicación
Gobernu Ireki eta Modernizazio Arloa / Área de Gobierno Abierto y Modernización

[cid:Escudo_7cbd05f0-d588-4757-9edb-9bd982e4fe2c.jpg]
[cid:bizi_7737e9f3-4d71-4a50-bdf8-7251a76e3760.jpg].    .

✆ +34944660218 / 3450<tel:3450>
✉ ***@***.******@***.***> Ⓦ www.getxo.eus<https://www.getxo.eus/>
[cid:ubicacion2_28d46b49-206c-4d8c-b19d-4ef2fe4c4a86.png] Basagoiti Etorbidea, 20 · 48992 · Getxo · Bizkaia


[cid:036_sm_fb_a1347472-45be-4a0b-af83-b901fa688c57.png]<https://www.facebook.com/GetxoUdala/>  [cid:logo-black_71f100eb-1275-4930-84b5-c65aa15e57ec.png] <https://twitter.com/getxoudala>   [cid:036_sm_y2_45d41b4c-7f16-42de-b619-b5cde39239df.png] <https://www.youtube.com/channel/UChEUKdARrLu5ylXvJFUrccQ>   <https://www.instagram.com/user_name_here> .
.

De: Liane Hampe ***@***.***
Enviado el: miércoles, 3 de enero de 2024 16:07
Para: xmera-circle/redmine_workload
CC: Julio Ortiz de Zarate Crespo; Mention
Asunto: Re: [xmera-circle/redmine_workload] [Bug]: Reserved word in postgres (Issue #34)


Hi @GetxoSystems<https://github.com/GetxoSystems>,

There should be no problem changing table column names and the code where these names are used.

Feel free to submit a Pull Request for this change.

We will be happy to merge it when it passes all the tests.

Best Regards
@liaham<https://github.com/liaham>

**Comment by liaham** [comment]
Perfect, @GetxoSystems! 

Then I close this issue.
