### ISSUE TITLE
[Bug]:  Incorrect Issue Display

### ISSUE THREAD

**Issue by koren85** [xmera-circle/redmine_workload#35]
### Contact Details

mailbobik@gmail.com

### What did you expect?

plugin work correct

### What has happend instead?

The issue text is not visible. 
![image](https://github.com/user-attachments/assets/dfd242be-126b-423e-b660-80a3d3948600)

### What could be a possible solution?

The issue text is not visible. However, after investigating the issue, I discovered that changing the opacity value in the CSS for the div.tooltip element from 0 to a higher value like 10 makes the task text appear. However, this adjustment leads to problems with tooltips becoming transparent.

div.tooltip {
    opacity: 100; /* Changing this to a higher value makes the text visible but affects tooltips */
}

### How can we reproduce the problem?

Install the plugin following the official instructions on redmine 4.1
go to workload page
Observe that the issue text is not visible.

### In what environment are you running the plugin?

Environment:
  Redmine version                4.1.3.stable
  Ruby version                   2.6.10-p210 (2022-04-12) [universal.arm64e-darwin23]
  Rails version                  5.2.5
  Environment                    development
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.39.3
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.5.7
  custom_menu                    1.9.0
  redmine_base_deface            1.5.3
 redmine_entity_generator       2016
  redmine_impersonate            2.0.0
  redmine_simple_managment       2023
  unread_issues                  2.2.4

### Version

2.2.1 (Latest)

### What browsers are you seeing the problem on?

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mboremski** [comment]
hey @koren85,
thank you for creating this report.
I have not been able to reproduce this with redmine 4.2.9 so far.
Right now I dont have a 4.1x on hand, but am pretty sure there also has not been such behaviour on this version.

I had a closer look on the plugins you have installed.
Some of them I cant find in the web. Like "redmine_simple_managment".
Some of them dont explicitly name compatibility with redmine 4.x or are outdated (like "redmine_entity_generator").

Are you able to do some tests to maybe find side-effects by one of your plugins?
Maybe this helps to repoduce this behaviour.

Thanks in advance

**Comment by liaham** [comment]
I close this issue since there is no response for more than 2 month.
