### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by konpega** [xmera-circle/redmine_workload#37]
Hi all
I am using Redmineplusagile 4.1.0.8.
When I tried to install I got the following warning and the system is not working now.

C:/Bitnami/redmineplusagile4108/apps/redmineplusagile/htdocs/plugins/redmine_contacts/init.rb:29: warning: already initialized constant FCSV
C:/Bitnami/redmineplusagile4108/apps/redmineplusagile/htdocs/plugins/redmine_agile/init.rb:29: warning: previous definition of FCSV was here
rake aborted!
SyntaxError: C:/Bitnami/redmineplusagile4108/apps/redmineplusagile/htdocs/plugins/redmine_workload/lib/redmine_workload/wl_date_tools.rb:86: syntax error, unexpected ..
...NationalHoliday.where(start: ..day).where(end: day..).empty?
...                             ^~
C:/Bitnami/redmineplusagile4108/apps/redmineplusagile/htdocs/plugins/redmine_workload/lib/redmine_workload/wl_date_tools.rb:86: syntax error, unexpected ')'
...start: ..day).where(end: day..).empty?

What may be the reason. 
If migration is not needed, at that moment system stopped the thin servers.

Tnaks in advance

**Comment by liaham** [comment]
Hi konpega,

Thank your for your report. 

Could you please submit your Ruby version your are running and what database you use: mariadb, mysql or postgresql.

There are restrictions for postgresql users. You can read it here in more detail: https://github.com/xmera-circle/redmine_workload?tab=readme-ov-file#workday-settings.

Best Regards,
liaham

**Comment by konpega** [comment]
Hi Liaham
I forgot to inform that I solved. When I look at detailly I found that there is ".." before and after "day" term. 

C:/Bitnami/redmineplusagile4108/apps/redmineplusagile/htdocs/plugins/redmine_workload/lib/redmine_workload/wl_date_tools.rb:86: syntax error, unexpected ..
...NationalHoliday.where(start: **..day**).where(end: **day..**).empty?

Then I deleted this "..".

It is solved. Maybe it is related with my version.
Redmine version                4.1.0.stable
  Ruby version                   2.5.7-p206 (2019-10-01) [x64-mingw32]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2

Thanks

**Comment by liaham** [comment]
Hi konpega,

Great that you have found a solution by yourself!

I would assume either your Ruby version 2.5 or Rails version 5.2 is not supporting the range syntax. 

Since Ruby is EOL: 2021-04-05 and Rails EOL: 2022-06-01 you should consider an upgrade for your Redmine instance.

Best Regards,
liaham
